image: node:8.1.2

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run build
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres:9.4
      environment:
        POSTGRES_PASSWORD: metacity
        POSTGRES_USER: metacity
        POSTGRES_DB: metacity_test
    elasticsearch:
      image: blacktop/elasticsearch:5.5
      environment:
        ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      ulimits:
         nofile:
            soft: 65536
            hard: 65536
      ports:
        - 9200:9200